// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQr_Te0YTujCMRKMGVKlT7Fu0VKqYJd-c',
    appId: '1:182404424989:web:c89f1fa26d57ae3fd8adf4',
    messagingSenderId: '182404424989',
    projectId: 'omr-master-project',
    authDomain: 'omr-master-project.firebaseapp.com',
    storageBucket: 'omr-master-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBr60MyuYNgeHY93UAWHZcFPL_KjinWtCw',
    appId: '1:182404424989:android:32c12d61dfe50ad2d8adf4',
    messagingSenderId: '182404424989',
    projectId: 'omr-master-project',
    storageBucket: 'omr-master-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyANF5upWBS5QGrinHcRv4QHQ2Ui1X811f0',
    appId: '1:182404424989:ios:ed5e2d787b2f5e4ed8adf4',
    messagingSenderId: '182404424989',
    projectId: 'omr-master-project',
    storageBucket: 'omr-master-project.appspot.com',
    iosBundleId: 'com.omrmaster.omrProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyANF5upWBS5QGrinHcRv4QHQ2Ui1X811f0',
    appId: '1:182404424989:ios:abee8fd967b56348d8adf4',
    messagingSenderId: '182404424989',
    projectId: 'omr-master-project',
    storageBucket: 'omr-master-project.appspot.com',
    iosBundleId: 'com.omrmaster.omrProject.RunnerTests',
  );
}
